/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.awt.Font;
import java.awt.font.TextAttribute;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author yan_t
 */
public class mainform extends javax.swing.JFrame {
    private String user_name;
    private int cod_user;
    /**
     * Creates new form mainform     */
    public mainform() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/parking.png")).getImage());
        logo.setSize(1024,720);
    }
    public void setusername(String name,int codigo){
        user_name = name;
        cod_user = codigo;
        username.setText(user_name);
        Font font = username.getFont();
        Map attributes = font.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        username.setFont(font.deriveFont(attributes));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainpanel = new javax.swing.JDesktopPane();
        username = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        logout = new javax.swing.JMenuItem();
        movimientos = new javax.swing.JMenu();
        m_ticker = new javax.swing.JMenuItem();
        m_pagar = new javax.swing.JMenuItem();
        m_cierre_caja = new javax.swing.JMenuItem();
        registros = new javax.swing.JMenu();
        regUsers = new javax.swing.JMenuItem();
        mtipos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainpanel.setBackground(new java.awt.Color(113, 184, 204));
        mainpanel.setToolTipText("");

        username.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        username.setForeground(java.awt.Color.green);
        username.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/User-blue.png"))); // NOI18N
        username.setText("Usuario:");

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/parkfast.jpg"))); // NOI18N
        logo.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        mainpanel.setLayer(username, javax.swing.JLayeredPane.DEFAULT_LAYER);
        mainpanel.setLayer(logo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout mainpanelLayout = new javax.swing.GroupLayout(mainpanel);
        mainpanel.setLayout(mainpanelLayout);
        mainpanelLayout.setHorizontalGroup(
            mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainpanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mainpanelLayout.setVerticalGroup(
            mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(159, 159, 159)
                .addComponent(logo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        file.setText("File");
        file.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        logout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/exit.png"))); // NOI18N
        logout.setText("Salir");
        logout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        logout.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        file.add(logout);
        logout.getAccessibleContext().setAccessibleDescription("");

        jMenuBar1.add(file);

        movimientos.setText("Movimientos");
        movimientos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        movimientos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        movimientos.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        movimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movimientosActionPerformed(evt);
            }
        });

        m_ticker.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        m_ticker.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ticket.png"))); // NOI18N
        m_ticker.setText("Ticker");
        m_ticker.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        m_ticker.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        m_ticker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_tickerActionPerformed(evt);
            }
        });
        movimientos.add(m_ticker);

        m_pagar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        m_pagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pay.png"))); // NOI18N
        m_pagar.setText("Pagar");
        m_pagar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        m_pagar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        m_pagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_pagarActionPerformed(evt);
            }
        });
        movimientos.add(m_pagar);

        m_cierre_caja.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        m_cierre_caja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/caja.png"))); // NOI18N
        m_cierre_caja.setText("Cierre Caja");
        m_cierre_caja.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        m_cierre_caja.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        m_cierre_caja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_cierre_cajaActionPerformed(evt);
            }
        });
        movimientos.add(m_cierre_caja);

        jMenuBar1.add(movimientos);

        registros.setText("Registros");
        registros.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        registros.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        registros.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        registros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrosActionPerformed(evt);
            }
        });

        regUsers.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        regUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/regUsers.png"))); // NOI18N
        regUsers.setText("Reg. Usuarios");
        regUsers.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        regUsers.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        regUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regUsersActionPerformed(evt);
            }
        });
        registros.add(regUsers);

        mtipos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mtipos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/types.png"))); // NOI18N
        mtipos.setText("Reg. tipos");
        mtipos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mtipos.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        mtipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mtiposActionPerformed(evt);
            }
        });
        registros.add(mtipos);

        jMenuBar1.add(registros);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainpanel, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainpanel)
        );

        mainpanel.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void movimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movimientosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_movimientosActionPerformed

    private void m_tickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_tickerActionPerformed
        // TODO add your handling code here:         
        genTicker fm = new genTicker();
        mainpanel.add(fm);
        fm.setCodigoUsuario(this.cod_user);
        fm.setVisible(true);
        fm.setLocation(480,150);
        fm.moveToFront();
    }//GEN-LAST:event_m_tickerActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        login lg = new login();
        lg.setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void m_pagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_pagarActionPerformed
        // TODO add your handling code here:
        pagos mf = new pagos();
        mainpanel.add(mf);
        mf.setVisible(true);
        mf.setLocation(410,30);
        mf.setCodigoUsuario(this.cod_user);
    }//GEN-LAST:event_m_pagarActionPerformed

    private void regUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regUsersActionPerformed
        // TODO add your handling code here:
        regUsuario mf = new regUsuario();
        mainpanel.add(mf);
        mf.setVisible(true);
        mf.setLocation(410,30);
        mf.setCodUser(cod_user);
    }//GEN-LAST:event_regUsersActionPerformed

    private void m_cierre_cajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_cierre_cajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_cierre_cajaActionPerformed

    private void registrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registrosActionPerformed

    private void mtiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mtiposActionPerformed
        // TODO add your handling code here:
        tipos mf = new tipos();
        mainpanel.add(mf);
        mf.setVisible(true);
        mf.setLocation(410,30);
        mf.setCodUser(cod_user);
    }//GEN-LAST:event_mtiposActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu file;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel logo;
    private javax.swing.JMenuItem logout;
    private javax.swing.JMenuItem m_cierre_caja;
    private javax.swing.JMenuItem m_pagar;
    private javax.swing.JMenuItem m_ticker;
    private javax.swing.JDesktopPane mainpanel;
    private javax.swing.JMenu movimientos;
    private javax.swing.JMenuItem mtipos;
    private javax.swing.JMenuItem regUsers;
    private javax.swing.JMenu registros;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
   
}
