/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import Clases.Utilidades;
import Clases.mysql;
import java.awt.Color;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.border.CompoundBorder;
import javax.swing.border.EmptyBorder;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yan_t
 */
public class tipos extends javax.swing.JInternalFrame {

    /**
     * Creates new form tipos
     */
    private int cod_user;
    private int jtabpanel;
    public tipos() {
        initComponents();
        this.editTiposUsuarios();
        this.editTiposParqueos();
        this.editTiposPagos();
    }
    public void setCodUser(int cod_user){
        this.cod_user = cod_user;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane_tipos = new javax.swing.JTabbedPane();
        jPanel_tiposUsuarios = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tuStatus = new javax.swing.JCheckBox();
        TuDescripcion = new javax.swing.JTextField();
        codigoTU = new javax.swing.JTextField();
        GuardarTu = new javax.swing.JButton();
        limpiarTu = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableTiposUsuarios = new JTable(){

            public boolean isCellEditable(int rowIndex, int colIndex) {

                return false; //Las celdas no son editables.

            }
        };
        jPanelTiposPagos = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtableTiposPagos = new JTable(){

            public boolean isCellEditable(int rowIndex, int colIndex) {

                return false; //Las celdas no son editables.

            }
        };
        codigoTP = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TpDescripcion = new javax.swing.JTextField();
        limpiarTP = new javax.swing.JButton();
        GuardarTP = new javax.swing.JButton();
        TpStatus = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jPanelTiposParqueos = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        codigoTParqueo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cantidad = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        DescripcionTParqueo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        precio = new javax.swing.JTextField();
        TparqueoStatus = new javax.swing.JCheckBox();
        jSeparator5 = new javax.swing.JSeparator();
        limpiarTParqueo = new javax.swing.JButton();
        GuardarTParqueo = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtableTiposParqueos = new JTable(){

            public boolean isCellEditable(int rowIndex, int colIndex) {

                return false; //Las celdas no son editables.

            }
        };

        setClosable(true);
        setIconifiable(true);
        setTitle("Tipos");
        setToolTipText("");
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        jTabbedPane_tipos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTabbedPane_tipos.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane_tiposStateChanged(evt);
            }
        });

        jPanel_tiposUsuarios.setToolTipText("Codigo Tipo Usuario");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Registro Tipos Usuarios");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Descripción:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Codigo:");

        tuStatus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tuStatus.setSelected(true);
        tuStatus.setText("Estado");

        codigoTU.setEditable(false);
        codigoTU.setText("0");
        codigoTU.setToolTipText("");

        GuardarTu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        GuardarTu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/save.png"))); // NOI18N
        GuardarTu.setText("Guardar");
        GuardarTu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarTuActionPerformed(evt);
            }
        });

        limpiarTu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        limpiarTu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/clean.png"))); // NOI18N
        limpiarTu.setText("Limpiar");
        limpiarTu.setMaximumSize(new java.awt.Dimension(105, 29));
        limpiarTu.setMinimumSize(new java.awt.Dimension(105, 29));
        limpiarTu.setPreferredSize(new java.awt.Dimension(105, 29));
        limpiarTu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarTuActionPerformed(evt);
            }
        });

        jtableTiposUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descripción", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtableTiposUsuarios.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jtableTiposUsuarios);
        if (jtableTiposUsuarios.getColumnModel().getColumnCount() > 0) {
            jtableTiposUsuarios.getColumnModel().getColumn(0).setResizable(false);
            jtableTiposUsuarios.getColumnModel().getColumn(0).setPreferredWidth(5);
            jtableTiposUsuarios.getColumnModel().getColumn(1).setResizable(false);
            jtableTiposUsuarios.getColumnModel().getColumn(1).setPreferredWidth(30);
            jtableTiposUsuarios.getColumnModel().getColumn(2).setResizable(false);
            jtableTiposUsuarios.getColumnModel().getColumn(2).setPreferredWidth(5);
        }

        javax.swing.GroupLayout jPanel_tiposUsuariosLayout = new javax.swing.GroupLayout(jPanel_tiposUsuarios);
        jPanel_tiposUsuarios.setLayout(jPanel_tiposUsuariosLayout);
        jPanel_tiposUsuariosLayout.setHorizontalGroup(
            jPanel_tiposUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel_tiposUsuariosLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(limpiarTu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(GuardarTu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_tiposUsuariosLayout.createSequentialGroup()
                .addGroup(jPanel_tiposUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel_tiposUsuariosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(tuStatus))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_tiposUsuariosLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_tiposUsuariosLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanel_tiposUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_tiposUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(codigoTU, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TuDescripcion))))
                .addGap(136, 136, 136))
        );
        jPanel_tiposUsuariosLayout.setVerticalGroup(
            jPanel_tiposUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_tiposUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(jPanel_tiposUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(codigoTU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_tiposUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TuDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(tuStatus)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanel_tiposUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(limpiarTu, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GuardarTu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
        );

        jTabbedPane_tipos.addTab("Tipos Usuarios", jPanel_tiposUsuarios);

        jtableTiposPagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descripción", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtableTiposPagos.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jtableTiposPagos);
        if (jtableTiposPagos.getColumnModel().getColumnCount() > 0) {
            jtableTiposPagos.getColumnModel().getColumn(0).setResizable(false);
            jtableTiposPagos.getColumnModel().getColumn(1).setResizable(false);
            jtableTiposPagos.getColumnModel().getColumn(2).setResizable(false);
        }

        codigoTP.setEditable(false);
        codigoTP.setText("0");
        codigoTP.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Codigo:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Descripción:");

        limpiarTP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        limpiarTP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/clean.png"))); // NOI18N
        limpiarTP.setText("Limpiar");
        limpiarTP.setMaximumSize(new java.awt.Dimension(105, 29));
        limpiarTP.setMinimumSize(new java.awt.Dimension(105, 29));
        limpiarTP.setPreferredSize(new java.awt.Dimension(105, 29));
        limpiarTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarTPActionPerformed(evt);
            }
        });

        GuardarTP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        GuardarTP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/save.png"))); // NOI18N
        GuardarTP.setText("Guardar");
        GuardarTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarTPActionPerformed(evt);
            }
        });

        TpStatus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TpStatus.setSelected(true);
        TpStatus.setText("Estado");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 255));
        jLabel6.setText("Registro Tipos Pagos");

        javax.swing.GroupLayout jPanelTiposPagosLayout = new javax.swing.GroupLayout(jPanelTiposPagos);
        jPanelTiposPagos.setLayout(jPanelTiposPagosLayout);
        jPanelTiposPagosLayout.setHorizontalGroup(
            jPanelTiposPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
            .addComponent(jSeparator3)
            .addComponent(jSeparator4)
            .addGroup(jPanelTiposPagosLayout.createSequentialGroup()
                .addGroup(jPanelTiposPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTiposPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelTiposPagosLayout.createSequentialGroup()
                            .addGap(146, 146, 146)
                            .addComponent(jLabel6))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTiposPagosLayout.createSequentialGroup()
                            .addGap(64, 64, 64)
                            .addGroup(jPanelTiposPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTiposPagosLayout.createSequentialGroup()
                                    .addGroup(jPanelTiposPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanelTiposPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(codigoTP, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TpDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(TpStatus, javax.swing.GroupLayout.Alignment.TRAILING))))
                    .addGroup(jPanelTiposPagosLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(limpiarTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(GuardarTP)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTiposPagosLayout.setVerticalGroup(
            jPanelTiposPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTiposPagosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(28, 28, 28)
                .addGroup(jPanelTiposPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelTiposPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TpDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(TpStatus)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTiposPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(limpiarTP, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GuardarTP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane_tipos.addTab("Tipos Pagos", jPanelTiposPagos);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 255));
        jLabel7.setText("Registro Tipos Parqueos");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Codigo:");

        codigoTParqueo.setEditable(false);
        codigoTParqueo.setText("0");
        codigoTParqueo.setToolTipText("Codigo");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Descripción:");

        cantidad.setToolTipText("Codigo");
        cantidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cantidadFocusLost(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Cantidad:");

        DescripcionTParqueo.setToolTipText("Codigo");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Precio:");

        precio.setToolTipText("Codigo");
        precio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                precioFocusLost(evt);
            }
        });

        TparqueoStatus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TparqueoStatus.setSelected(true);
        TparqueoStatus.setText("Estado");

        limpiarTParqueo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        limpiarTParqueo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/clean.png"))); // NOI18N
        limpiarTParqueo.setText("Limpiar");
        limpiarTParqueo.setMaximumSize(new java.awt.Dimension(105, 29));
        limpiarTParqueo.setMinimumSize(new java.awt.Dimension(105, 29));
        limpiarTParqueo.setPreferredSize(new java.awt.Dimension(105, 29));
        limpiarTParqueo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarTParqueoActionPerformed(evt);
            }
        });

        GuardarTParqueo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        GuardarTParqueo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/save.png"))); // NOI18N
        GuardarTParqueo.setText("Guardar");
        GuardarTParqueo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarTParqueoActionPerformed(evt);
            }
        });

        jtableTiposParqueos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descripción", "Cantidad", "Precio", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtableTiposParqueos.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jtableTiposParqueos);
        if (jtableTiposParqueos.getColumnModel().getColumnCount() > 0) {
            jtableTiposParqueos.getColumnModel().getColumn(0).setResizable(false);
            jtableTiposParqueos.getColumnModel().getColumn(1).setResizable(false);
            jtableTiposParqueos.getColumnModel().getColumn(2).setResizable(false);
            jtableTiposParqueos.getColumnModel().getColumn(3).setResizable(false);
            jtableTiposParqueos.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout jPanelTiposParqueosLayout = new javax.swing.GroupLayout(jPanelTiposParqueos);
        jPanelTiposParqueos.setLayout(jPanelTiposParqueosLayout);
        jPanelTiposParqueosLayout.setHorizontalGroup(
            jPanelTiposParqueosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTiposParqueosLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanelTiposParqueosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelTiposParqueosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codigoTParqueo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelTiposParqueosLayout.createSequentialGroup()
                        .addGroup(jPanelTiposParqueosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelTiposParqueosLayout.createSequentialGroup()
                                .addComponent(DescripcionTParqueo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10))
                            .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelTiposParqueosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cantidad)
                            .addComponent(TparqueoStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator5)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTiposParqueosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelTiposParqueosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTiposParqueosLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(121, 121, 121))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTiposParqueosLayout.createSequentialGroup()
                        .addComponent(limpiarTParqueo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(GuardarTParqueo)
                        .addGap(50, 50, 50))))
            .addGroup(jPanelTiposParqueosLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jSeparator6))
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
        );
        jPanelTiposParqueosLayout.setVerticalGroup(
            jPanelTiposParqueosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTiposParqueosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanelTiposParqueosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(codigoTParqueo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTiposParqueosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(DescripcionTParqueo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTiposParqueosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TparqueoStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTiposParqueosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(limpiarTParqueo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GuardarTParqueo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE))
        );

        jTabbedPane_tipos.addTab("Tipos Parqueos", jPanelTiposParqueos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane_tipos)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane_tipos, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane_tiposStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane_tiposStateChanged
        // TODO add your handling code here:
       jtabpanel = this.jTabbedPane_tipos.getSelectedIndex();
       this.buscarRegistros("");
    }//GEN-LAST:event_jTabbedPane_tiposStateChanged

    private void limpiarTuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarTuActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_limpiarTuActionPerformed

    private void limpiarTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarTPActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_limpiarTPActionPerformed

    private void GuardarTuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarTuActionPerformed
        // TODO add your handling code here:
        if(!"".equals(TuDescripcion.getText().trim())){
            TuDescripcion.setBorder(codigoTU.getBorder());
            String query = "call p_actualizarTiposUsuarios("+codigoTU.getText()+",'"+TuDescripcion.getText().trim()+"',"+tuStatus.isSelected()+")";
            ActualizarDatos(query);
        }else{
            Color color = new Color(255,51,102);
            TuDescripcion.setBorder(new CompoundBorder(new EmptyBorder(3, 3, 4, 4), new LineBorder(color, 1)));
            JOptionPane.showMessageDialog(null, "Campos marcados Obligatorios");
            TuDescripcion.setToolTipText("Campo Obligatorio!");
        }
    }//GEN-LAST:event_GuardarTuActionPerformed

    private void GuardarTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarTPActionPerformed
        // TODO add your handling code here:
        if(!"".equals(TpDescripcion.getText().trim())){
            TpDescripcion.setBorder(codigoTP.getBorder());
            String query = "call p_actualizarTiposPagos("+codigoTP.getText()+",'"+TpDescripcion.getText().trim()+"',"+TpStatus.isSelected()+")";
            ActualizarDatos(query);
        }else{
            Color color = new Color(255,51,102);
            TpDescripcion.setBorder(new CompoundBorder(new EmptyBorder(3, 3, 4, 4), new LineBorder(color, 1)));
            JOptionPane.showMessageDialog(null, "Campos marcados Obligatorios");
            TpDescripcion.setToolTipText("Campo Obligatorio!");
        }
    }//GEN-LAST:event_GuardarTPActionPerformed

    private void limpiarTParqueoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarTParqueoActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_limpiarTParqueoActionPerformed

    private void GuardarTParqueoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarTParqueoActionPerformed
        // TODO add your handling code here:
        if(DescripcionTParqueo.getText().trim().isEmpty() && cantidad.getText().trim().isEmpty() && precio.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Los campos marcados obligatorios!");
            Color color = new Color(255,51,102);
            DescripcionTParqueo.setBorder(new CompoundBorder(new EmptyBorder(3, 3, 4, 4), new LineBorder(color, 1)));
            cantidad.setBorder(new CompoundBorder(new EmptyBorder(3, 3, 4, 4), new LineBorder(color, 1)));
            precio.setBorder(new CompoundBorder(new EmptyBorder(3, 3, 4, 4), new LineBorder(color, 1)));
            DescripcionTParqueo.requestFocus();
        }else{
            DescripcionTParqueo.setBorder(codigoTParqueo.getBorder());
            cantidad.setBorder(codigoTParqueo.getBorder());
            precio.setBorder(codigoTParqueo.getBorder());
            String query = "call p_actualizarTiposParqueos("+codigoTParqueo.getText()+",'"+DescripcionTParqueo.getText().trim()+"',"+cantidad.getText().trim()+","+precio.getText().trim()+","+cod_user+","+TparqueoStatus.isSelected()+")";
            ActualizarDatos(query);
        }
    }//GEN-LAST:event_GuardarTParqueoActionPerformed

    private void cantidadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidadFocusLost
        // TODO add your handling code here:
        if(!"".equals(cantidad.getText().trim())){
            if(!Utilidades.isNumeric(cantidad.getText())){
                cantidad.setText("");
                Color color = new Color(255,51,102);
                cantidad.setBorder(new CompoundBorder(new EmptyBorder(3, 3, 4, 4), new LineBorder(color, 1)));
                cantidad.setToolTipText("Campo Numerico!");
                cantidad.requestFocus();
            }else{
                cantidad.setBorder(codigoTParqueo.getBorder());
            }
        }else{
            cantidad.setBorder(codigoTParqueo.getBorder());
        }
    }//GEN-LAST:event_cantidadFocusLost

    private void precioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_precioFocusLost
        // TODO add your handling code here:
        if(!"".equals(precio.getText().trim())){
            if(!Utilidades.isNumeric(precio.getText())){
                precio.setText("");
                Color color = new Color(255,51,102);
                precio.setBorder(new CompoundBorder(new EmptyBorder(3, 3, 4, 4), new LineBorder(color, 1)));
                precio.setToolTipText("Campo Numerico!");
                precio.requestFocus();
            }else{
                precio.setBorder(codigoTParqueo.getBorder());
            }
        }else{
            precio.setBorder(codigoTParqueo.getBorder());
        }
    }//GEN-LAST:event_precioFocusLost
    private void limpiar(){
        switch(jtabpanel){
            case 0:
                codigoTU.setText("0");
                TuDescripcion.setText("");
                TuDescripcion.setBorder(codigoTU.getBorder());
                tuStatus.setSelected(true);
                break;
            case 1:
                codigoTP.setText("0");
                TpDescripcion.setText("");
                TpDescripcion.setBorder(codigoTP.getBorder());
                TpStatus.setSelected(true);
                break;
            case 2:
                codigoTParqueo.setText("0");
                DescripcionTParqueo.setText("");
                DescripcionTParqueo.setBorder(codigoTParqueo.getBorder());
                cantidad.setText("");
                cantidad.setBorder(codigoTParqueo.getBorder());
                precio.setText("");
                precio.setBorder(codigoTParqueo.getBorder());
                TparqueoStatus.setSelected(true);
                break;
        }
    }
    
    public void buscarRegistros(String texto){
        String query = "";
        query = (jtabpanel==0)?"call p_listarTiposUsuarios('"+texto.trim()+"')":(jtabpanel==1)?"call p_listarTiposPagos('"+texto.trim()+"')":(jtabpanel==2)?"call p_listarTiposParqueos('"+texto.trim()+"')":"";
        mysql cn = new mysql();
        ResultSet rs = cn.ejecutar(query);
        cn.desconectar();
        DefaultTableModel model1 = (DefaultTableModel)((jtabpanel==0)?jtableTiposUsuarios.getModel():(jtabpanel==1)?jtableTiposPagos.getModel():(jtabpanel==2)?jtableTiposParqueos.getModel():null);
        model1.setNumRows(0);
        try {
            while(rs.next()){
                if(jtabpanel==0) model1.addRow(new Object[]{rs.getString("codigo"),rs.getString("descripcion"),rs.getString("estado")});
                if(jtabpanel==1) model1.addRow(new Object[]{rs.getString("codigo"),rs.getString("descripcion"),rs.getString("estado")});
                if(jtabpanel==2) model1.addRow(new Object[]{rs.getString("codigo"),rs.getString("descripcion"),rs.getString("cantidad"),rs.getString("precio"),rs.getString("estado")});
            }
        } catch (SQLException ex) {
            Logger.getLogger(regUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void editTiposUsuarios(){
        jtableTiposUsuarios.addMouseListener(new MouseAdapter(){
            @Override
            public void mousePressed(MouseEvent me){
                JTable table = (JTable) me.getSource();
                Point p = me.getPoint();
                int row = table.rowAtPoint(p);
                if(me.getClickCount() == 2){
                    DefaultTableModel model1 = (DefaultTableModel) jtableTiposUsuarios.getModel();
                    int index = jtableTiposUsuarios.getSelectedRow();
                    codigoTU.setText(jtableTiposUsuarios.getValueAt(index, 0).toString());
                    TuDescripcion.setText(jtableTiposUsuarios.getValueAt(index, 1).toString());
                    tuStatus.setSelected(("1".equals(jtableTiposUsuarios.getValueAt(index,2).toString())));
                }
            }
        });
    }
    private void editTiposParqueos(){
        jtableTiposParqueos.addMouseListener(new MouseAdapter(){
            @Override
            public void mousePressed(MouseEvent me){
                JTable table = (JTable) me.getSource();
                Point p = me.getPoint();
                int row = table.rowAtPoint(p);
                if(me.getClickCount() == 2){
                    DefaultTableModel model1 = (DefaultTableModel) jtableTiposParqueos.getModel();
                    int index = jtableTiposParqueos.getSelectedRow();
                    codigoTParqueo.setText(jtableTiposParqueos.getValueAt(index, 0).toString());
                    DescripcionTParqueo.setText(jtableTiposParqueos.getValueAt(index, 1).toString());
                    cantidad.setText(jtableTiposParqueos.getValueAt(index, 2).toString());
                    precio.setText(jtableTiposParqueos.getValueAt(index, 3).toString());
                    TparqueoStatus.setSelected(("1".equals(jtableTiposParqueos.getValueAt(index,4).toString())));
                }
            }
        });
    }
    private void ActualizarDatos(String query){
        mysql cn = new mysql();
        ResultSet rs = cn.ejecutar(query);
        cn.desconectar();
        try {
            if(rs.next()){
               JOptionPane.showMessageDialog(null, rs.getString("mensaje"));
                buscarRegistros("");
                limpiar();
            }else{
                JOptionPane.showMessageDialog(null,"Problemas con el servidor!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(tipos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void editTiposPagos(){
        jtableTiposPagos.addMouseListener(new MouseAdapter(){
            @Override
            public void mousePressed(MouseEvent me){
                JTable table = (JTable) me.getSource();
                Point p = me.getPoint();
                int row = table.rowAtPoint(p);
                if(me.getClickCount() == 2){
                    DefaultTableModel model1 = (DefaultTableModel) jtableTiposPagos.getModel();
                    int index = jtableTiposPagos.getSelectedRow();
                    codigoTP.setText(jtableTiposPagos.getValueAt(index, 0).toString());
                    TpDescripcion.setText(jtableTiposPagos.getValueAt(index, 1).toString());
                    TpStatus.setSelected(("1".equals(jtableTiposPagos.getValueAt(index,2).toString())));
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DescripcionTParqueo;
    private javax.swing.JButton GuardarTP;
    private javax.swing.JButton GuardarTParqueo;
    private javax.swing.JButton GuardarTu;
    private javax.swing.JTextField TpDescripcion;
    private javax.swing.JCheckBox TpStatus;
    private javax.swing.JCheckBox TparqueoStatus;
    private javax.swing.JTextField TuDescripcion;
    private javax.swing.JTextField cantidad;
    private javax.swing.JTextField codigoTP;
    private javax.swing.JTextField codigoTParqueo;
    private javax.swing.JTextField codigoTU;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelTiposPagos;
    private javax.swing.JPanel jPanelTiposParqueos;
    private javax.swing.JPanel jPanel_tiposUsuarios;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTabbedPane jTabbedPane_tipos;
    private javax.swing.JTable jtableTiposPagos;
    private javax.swing.JTable jtableTiposParqueos;
    private javax.swing.JTable jtableTiposUsuarios;
    private javax.swing.JButton limpiarTP;
    private javax.swing.JButton limpiarTParqueo;
    private javax.swing.JButton limpiarTu;
    private javax.swing.JTextField precio;
    private javax.swing.JCheckBox tuStatus;
    // End of variables declaration//GEN-END:variables
}
